name: automation_gateway_request with BigQuery Iceberg destination

source:
  name: kafka
  stream: topic
  sync_mode: stream
  force_ignore_checkpoint: false
  topics:
    - "destination_id": "automation_gateway_request_iceberg"
      "name": "events.ml.automation-gateway.request"

  nb_bytes_schema_id: 4
  message_encoding: utf-8
  timestamp_ms_name: ts_ms
  batch_size: 1000
  consumer_timeout: 20
  bootstrap_servers: pkc-n3603.us-central1.gcp.confluent.cloud:9092
  group_id: dataops-iceberg
  authentication:
    type: basic
    schema_registry_url: https://apicurio-us-central1.global.gorgias.com
    schema_registry_username: gorgias
    schema_registry_password: nD2rC@62CpPtj%lx
    params:
      username: EMP32WJHLYYYWGGG
      password: a12XXhuQ6ae6I2htNgwJ3DFZz0slxRQin/i7xGZACFsTNH0ZqallJU/8KjWbjWN5

destination:
  name: bigquery_iceberg
  config:
    # BigQuery Configuration
    project_id: gorgias-growth-development
    dataset_id: bizon_iceberg
    dataset_location: US

    # GCS Configuration for Iceberg Data
    gcs_warehouse_bucket: gorgias-iceberg-warehouse
    gcs_warehouse_path: iceberg/warehouse

    # Iceberg Table Configuration
    table_format: parquet  # Options: parquet, orc, avro
    target_file_size_mb: 128
    write_batch_size: 1000
    iceberg_namespace: bizon  # Iceberg namespace (default: bizon)
    
    # Retry Configuration for Rate Limits and Transient Errors
    max_retry_attempts: 3      # Maximum retry attempts (default: 3)
    retry_backoff_base: 2.0    # Exponential backoff base (default: 2.0)
    retry_backoff_max: 60      # Maximum backoff time in seconds (default: 60)

    # Partitioning Configuration (optional)
    time_partitioning:
      - field: "_bizon_loaded_at"  # Time-based partitioning 
        type: DAY                  # Options: YEAR, MONTH, DAY, HOUR

    # Destination Table Configuration (optional - uses defaults if not specified)
    destination_table_config:
      - destination_id: "automation_gateway_request_iceberg"
        clustering_keys: ["domain_name", "user_id"]  # Fields used as partition keys
        iceberg_schema:
          # Simplified field configuration with Iceberg types
          # If not specified, uses default Bizon field mapping
          - name: user_id
            type: long
          - name: domain_name
            type: string
          - name: request_type
            type: string
          # Bizon fields use defaults if not specified:
          # bizon_extracted_at -> _bizon_extracted_at (timestamp)
          # bizon_loaded_at -> _bizon_loaded_at (timestamp)
          # source_data -> _source_data (string)

    # BigLake Configuration
    biglake_connection_id: us.biglake-connection

    # Iceberg Catalog Configuration
    catalog_config:
      default:
        type: sql
        uri: postgresql+psycopg2://iceberg:password@postgres-server:5432/iceberg_catalog
        init_catalog_tables: true

    # Authentication (optional - uses environment credentials if not provided)
    authentication:
      service_account_key: ""  # JSON string or leave empty to use environment

# Alternative catalog configurations:

# For REST Catalog:
# catalog_config:
#   production:
#     type: rest
#     uri: http://iceberg-catalog:8181
#     warehouse: gs://gorgias-iceberg-warehouse/iceberg

# For File-based Catalog (Hive):
# catalog_config:
#   default:
#     type: hive  
#     warehouse: gs://gorgias-iceberg-warehouse/iceberg